# Autogenerated wrapper script for TDLib_jll for aarch64-apple-darwin
export libtdjson

using OpenSSL_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("TDLib")
JLLWrappers.@declare_library_product(libtdjson, "@rpath/libtdjson.1.8.24.dylib")
function __init__()
    JLLWrappers.@generate_init_header(OpenSSL_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libtdjson,
        "lib/libtdjson.1.8.24.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
